FashionShop/Controllers/FeaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class FeaturesController : Controller
    {
        // GET: Features
        public ActionResult shoping_cart()
        {
            return View();
        }

        public ActionResult Checkout()
        {
            return View();
        }
    }
}

FashionShop/Views/Features/shoping_cart.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Shopping Cart";
}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Shopping Cart</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Shopping Cart</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Cart Start -->
<div class="container-fluid px-xl-5">
    <div class="mb-5">
        <div class="card border-secondary">
            <div class="card-body">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Select</th>
                            <th>Image</th>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        <!-- Example Product Row -->
                        <tr>
                            <td class="align-middle">
                                <div class="custom-control custom-checkbox custom-control-inline">
                                    <input type="checkbox" class="custom-control-input product-checkbox" id="product-1" name="product">
                                    <label class="custom-control-label" for="product-1">Chọn</label>
                                </div>
                            </td>
                            <td class="align-middle"><img src="img/product-1.jpg" alt="" style="width: 50px; height: 50px; object-fit: cover;"></td>
                            <td class="align-middle">Colorful Stylish Shirt</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button></td>
                        </tr>

                        <tr>
                            <td class="align-middle">
                                <div class="custom-control custom-checkbox custom-control-inline">
                                    <input type="checkbox" class="custom-control-input product-checkbox" id="product-2" name="product">
                                    <label class="custom-control-label" for="product-2">Chọn</label>
                                </div>
                            </td>
                            <td class="align-middle"><img src="img/product-1.jpg" alt="" style="width: 50px; height: 50px; object-fit: cover;"></td>
                            <td class="align-middle">Colorful Stylish Shirt</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button></td>
                        </tr>

                        <tr>
                            <td class="align-middle">
                                <div class="custom-control custom-checkbox custom-control-inline">
                                    <input type="checkbox" class="custom-control-input product-checkbox" id="product-3" name="product">
                                    <label class="custom-control-label" for="product-3">Chọn</label>
                                </div>
                            </td>
                            <td class="align-middle"><img src="img/product-1.jpg" alt="" style="width: 50px; height: 50px; object-fit: cover;"></td>
                            <td class="align-middle">Colorful Stylish Shirt</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button></td>
                        </tr>
                        <!-- Repeat similar rows for other products -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="errorMessage" class="alert alert-danger" hidden>
        <div class="row align-items-center">
            <div class="col-auto">
                <i class="fa-solid fa-circle-info"></i>
            </div>
            <div class="col">
                <span class="error-message"></span>
            </div>
        </div>
    </div>

    <div class="mb-5">
        <div class="card border-secondary sticky-card" id="cartSummaryCard">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="custom-control custom-checkbox custom-control-inline">
                                <input type="checkbox" class="custom-control-input" id="selectAll">
                                <label class="custom-control-label" for="selectAll">Chọn tất cả</label>
                            </div>
                            <button class="btn btn-link btn-sm" id="DeleteProduct" data-toggle="modal" data-target="#confirmDeleteModal">Xóa</button>
                            <button class="btn btn-link btn-sm" data-toggle="modal" data-target="#discountCodeModal" style="color: #0056b3; border: none;">Chọn hoặc nhập mã</button>
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <div class="row">
                            <div class="col-md-8">
                                <p class="mb-1 text-right">Tổng tiền thanh toán: <strong>$160</strong></p>
                                <p class="mb-0 text-right">Số tiền tiết kiệm: <strong>$20</strong></p>
                            </div>
                            <div class="col-md-4">
                                <button class="btn btn-success btn-block py-2" id="purchase" data-redirect-url="@Url.Action("Checkout", "Features")">Mua hàng</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Xác nhận Xóa -->
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Xác Nhận Xóa</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Bạn chắc chắn muốn xóa <span id="productCount">0</span> sản phẩm đã chọn khỏi giỏ hàng?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-danger" id="confirmDeleteBtn">Có, xóa sản phẩm</button>
                </div>
            </div>
        </div>
    </div>

    @Html.Partial("SelectVoucher")
</div>
<!-- Cart End -->