FashionShop/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult contact()
        {
            return View();
        }
    }
}

FashionShop/Controllers/MyAccountController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FashionShop.Models.LeDucThien.ThienProcessData;
using FashionShop.Models.LeDucThien.ThienEntity;


namespace FashionShop.Controllers
{
    public class MyAccountController : Controller
    {
        
        [HttpPost]
        public ActionResult CapNhatHoSo(string username, string firstname, string lastname, int day, int month, int year, string gender)
        {
            try
            {
                // Khởi tạo lớp xử lý
                pd_KhachHang khachHangProcess = new pd_KhachHang();

                // Gọi phương thức cập nhật mà không truyền mật khẩu và ảnh
                khachHangProcess.CapNhatKhachHang(username, firstname, lastname, day, month, year, gender);

                // Thêm thông báo thành công
                TempData["SuccessMessage"] = "Cập nhật thông tin thành công!";
            }
            catch (Exception ex)
            {
                // Xử lý lỗi và thông báo lỗi
                TempData["ErrorMessage"] = "Có lỗi xảy ra: " + ex.Message;
            }

            // Trả về lại trang Hồ Sơ
            return RedirectToAction("HoSo");
        }

        [HttpPost]
        public ActionResult CapNhatAnhHoSo(HttpPostedFileBase avatar)
        {
            try
            {
                if (avatar != null && avatar.ContentLength > 0)
                {
                    // Xác định đường dẫn lưu ảnh
                    var fileName = Path.GetFileName(avatar.FileName);
                    var path = Path.Combine(Server.MapPath("~/img"), fileName);

                    // Lưu ảnh vào thư mục "img"
                    avatar.SaveAs(path);

                    // Lấy tên ảnh đã lưu và cập nhật trong cơ sở dữ liệu
                    string username = User.Identity.Name;  // Lấy username của người dùng đang đăng nhập
                    pd_KhachHang khachHangProcess = new pd_KhachHang();
                    khachHangProcess.CapNhatAnhKhachHang(username, fileName); // Cập nhật ảnh trong cơ sở dữ liệu

                    TempData["SuccessMessage"] = "Cập nhật ảnh thành công!";
                    TempData["ShowModal"] = true;  // Thêm thông tin để hiển thị modal

                }
                else
                {
                    TempData["ErrorMessage"] = "Vui lòng chọn ảnh!";
                    TempData["ShowModal"] = false; // Không hiển thị modal khi có lỗi
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Có lỗi xảy ra khi cập nhật ảnh: " + ex.Message;
            }

            // Quay lại trang Hồ Sơ
            return RedirectToAction("HoSo");
        }

        [HttpPost]
        public ActionResult ThayDoiMatKhau(string oldPassword, string newPassword, string confirmPassword)
        {
            HttpCookie usernameCookie = Request.Cookies["Username"];
            var username = usernameCookie != null ? usernameCookie.Value : string.Empty;

            // Khởi tạo lớp xử lý dữ liệu người dùng
            pd_KhachHang khachHangProcess = new pd_KhachHang();

            // Lấy thông tin người dùng từ cơ sở dữ liệu
            var user = khachHangProcess.GetAccountUsers().FirstOrDefault(u => u.Username == username);

            // Kiểm tra mật khẩu cũ có chính xác không
            if (oldPassword != user.MatKhau)
            {
                TempData["ErrorMessage"] = "Mật khẩu cũ không chính xác.";
                return RedirectToAction("MatKhau");
            }

            // Kiểm tra mật khẩu mới không trùng mật khẩu cũ
            if (newPassword == oldPassword)
            {
                TempData["ErrorMessage"] = "Mật khẩu mới không thể trùng với mật khẩu cũ.";
                return RedirectToAction("MatKhau");
            }

            // Kiểm tra mật khẩu xác nhận có trùng mật khẩu mới không
            if (confirmPassword != newPassword)
            {
                TempData["ErrorMessage"] = "Mật khẩu mới và mật khẩu xác nhận không trùng nhau.";
                return RedirectToAction("MatKhau");
            }

            // Cập nhật mật khẩu mới
            khachHangProcess.CapNhatMatKhau(username, newPassword);

            TempData["SuccessMessage"] = "Mật khẩu đã được cập nhật thành công.";

            // Trả về trang ThayDoiMatKhau
            return RedirectToAction("MatKhau");
        }


        // GET: MyAccount
        public ActionResult HoSo()
        {
            // Giả sử bạn lấy thông tin từ Cookie hoặc Database
            HttpCookie usernameCookie = Request.Cookies["Username"];
            var username = usernameCookie != null ? usernameCookie.Value : string.Empty;

            pd_KhachHang khachHangProcess = new pd_KhachHang();

            // Truy vấn thông tin người dùng từ cơ sở dữ liệu theo tên đăng nhập
            var user = khachHangProcess.GetKhachHangWhere(username).FirstOrDefault();

            // Lưu trữ các giá trị vào ViewBag để gửi sang View
            ViewBag.Username = user.Username;
            ViewBag.FirstName = user.FirstName;
            ViewBag.LastName = user.LastName;
            ViewBag.Gender = user.Gender;
            ViewBag.Day = user.Day;
            ViewBag.Month = user.Moth;
            ViewBag.Year = user.Year;
            ViewBag.Avatar = user.Anh;

            return View();
        }

        [HttpGet]
        public JsonResult GetChiNhanhByNganHang(int maNganHangLienKet)
        {
            try
            {
                // Gọi lớp xử lý dữ liệu chi nhánh ngân hàng
                pd_ChiNhanhNganHang chiNhanhProcess = new pd_ChiNhanhNganHang();
                List<ent_ChiNhanhNganHang> chiNhanhList = chiNhanhProcess.GetTenChiNhanh(maNganHangLienKet);

                // Nếu không có chi nhánh nào, trả về thông báo lỗi
                if (chiNhanhList == null || !chiNhanhList.Any())
                {
                    return Json(new { success = false, message = "Không tìm thấy chi nhánh!" }, JsonRequestBehavior.AllowGet);
                }

                // Trả về danh sách chi nhánh
                return Json(new { success = true, data = chiNhanhList }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult GetTenChuSoHuuBySoTaiKhoan(string soTaiKhoan, int maNganHangLienKet)
        {
            try
            {
                pd_TaiKhoanNganHangDuocLienKet taiKhoanProcess = new pd_TaiKhoanNganHangDuocLienKet();
                string tenChuSoHuu = taiKhoanProcess.GetTenChuSoHuuBySoTaiKhoan(soTaiKhoan, maNganHangLienKet);

                if (string.IsNullOrEmpty(tenChuSoHuu))
                {
                    return Json(new { success = false, message = "Không tồn tại tài khoản này" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = true, tenChuSoHuu = tenChuSoHuu }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult AddBankAccount(string maNganHangLienKet, string soTaiKhoan, string tenChuSoHuu, string tenChiNhanh)
        {
            try
            {
                // Lấy thông tin username từ Cookie
                HttpCookie usernameCookie = Request.Cookies["Username"];
                var username = usernameCookie != null ? usernameCookie.Value : string.Empty;
                var maNganHang = Convert.ToInt32(maNganHangLienKet);

                // Kiểm tra nếu username không hợp lệ
                if (string.IsNullOrEmpty(username))
                {
                    return Json(new { success = false, message = "Không tìm thấy thông tin người dùng." });
                }

                // Kiểm tra thông tin tài khoản
                if (string.IsNullOrEmpty(soTaiKhoan) || string.IsNullOrEmpty(tenChuSoHuu) || string.IsNullOrEmpty(tenChiNhanh))
                {
                    return Json(new { success = false, message = "Vui lòng nhập đầy đủ thông tin tài khoản." });
                }

                // Tạo đối tượng để truyền vào phương thức ThemTaiKhoanNganHang
                var taiKhoan = new ent_ThemTaiKhoanNganHang
                {
                    MaAccount = username,
                    MaNganHangLienKet = maNganHang,
                    SoTaiKhoan = soTaiKhoan,
                    TenChuSoHuu = tenChuSoHuu,
                    TenChiNhanh = tenChiNhanh
                };

                // Khởi tạo lớp xử lý dữ liệu
                pd_TaiKhoanNganHangCuaToi taiKhoanProcess = new pd_TaiKhoanNganHangCuaToi();

                // Gọi phương thức thêm tài khoản ngân hàng
                taiKhoanProcess.ThemTaiKhoanNganHang(taiKhoan);

                return Json(new { success = true, message = "Thêm tài khoản ngân hàng thành công!" });
            }
            catch (Exception ex)
            {
                // Xử lý lỗi
                return Json(new { success = false, message = "Có lỗi xảy ra khi thêm tài khoản ngân hàng. Lỗi: " + ex.Message });
            }
        }


        [HttpPost]
        public ActionResult XoaTaiKhoanNganHang(int BankID)
        {
            try
            {
                pd_TaiKhoanNganHangCuaToi taiKhoanNganHangCuaToiProcees = new pd_TaiKhoanNganHangCuaToi();
                // Thực hiện xóa tài khoản ngân hàng với ID = BankID
                taiKhoanNganHangCuaToiProcees.DeleteTaiKhoanNganHangCuaToi(BankID);
              
                TempData["SuccessMessage"] = "Xóa tài khoản ngân hàng thành công!";
             
            }
            catch (Exception ex)
            {

FashionShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult order()
        {
            ViewBag.TrangThai = "Hoàn thành";
            return View();
        }

        public ActionResult ChiTietDonHang()
        {
            ViewBag.TrangThai = "Hoàn thành";
            return View();
        }

        public ActionResult ChiTietHuyDonHang()
        {
            ViewBag.TrangThai = "Đã hủy";
            return View();
        }
    }
}

FashionShop/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult product()
        {
            return View();
        }

        public ActionResult product_detail()
        {
            return View();
        }
    }
}

FashionShop/Controllers/VoucherController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FashionShop.Models.LeDucThien.ThienProcessData;
using FashionShop.Models.LeDucThien.ThienEntity;

namespace FashionShop.Controllers
{
    public class VoucherController : Controller
    {
        // GET: Voucher
        public ActionResult voucher()
        {
            // Giả sử bạn lấy thông tin từ Cookie hoặc Database
            HttpCookie usernameCookie = Request.Cookies["Username"];
            var username = usernameCookie != null ? usernameCookie.Value : string.Empty;

            pd_VoucherCuaToi voucherProcess = new pd_VoucherCuaToi();

            List<ent_VoucherCuaToi> ent_VoucherCuaTois = voucherProcess.GetVoucherCuaToi(username);
;
            ViewBag.voucherCuaToi = ent_VoucherCuaTois;
            return View();
        }

        [HttpPost]
        public ActionResult ThemVoucher(string maVoucher)
        {
            if (!string.IsNullOrEmpty(maVoucher))
            {
                HttpCookie usernameCookie = Request.Cookies["Username"];
                var username = usernameCookie != null ? usernameCookie.Value : string.Empty;

                pd_VoucherCuaToi voucherProcess = new pd_VoucherCuaToi();
                voucherProcess.ThemMaVoucherCuaToi(maVoucher, username);

                // Sau khi thêm thành công, trả lại trang Index
                return RedirectToAction("voucher");
            }

            // Nếu mã voucher không hợp lệ, vẫn trả về trang Index
            return RedirectToAction("voucher");
        }
    }
}

FashionShop/Views/Shared/ModalDanhGia.cshtml
@{
    Layout = null;
}

<!-- Modal Đánh Giá -->
<div class="modal fade" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="reviewModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="reviewModalLabel">Đánh Giá Đơn Hàng</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="rating">Đánh giá:</label>
                        <select class="form-control" id="rating">
                            <option value="5">5 </option>
                            <option value="4">4</option>
                            <option value="3">3</option>
                            <option value="2">2</option>
                            <option value="1">1</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="review">Nhận xét:</label>
                        <textarea class="form-control" id="review" rows="3"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-primary">Gửi Đánh Giá</button>
            </div>
        </div>
    </div>
</div>

FashionShop/Views/Shared/ModalMuaLai.cshtml
@{
    Layout = null;
}

<!-- Modal Mua Lại -->
<div class="modal fade" id="reorderModal" tabindex="-1" role="dialog" aria-labelledby="reorderModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="reorderModalLabel">Mua Lại Sản Phẩm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Bạn chắc chắn muốn mua lại sản phẩm này?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-success">Mua lại</button>
            </div>
        </div>
    </div>
</div>

FashionShop/Views/Shared/ModalXacNhanHuyDon.cshtml
@{
    Layout = null;
}

<!-- Modal Xác Nhận Hủy -->
<div class="modal fade" id="cancelConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="cancelConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cancelConfirmationModalLabel">Xác Nhận Hủy Đơn Hàng</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Bạn chắc chắn muốn hủy đơn hàng này?</p>

                <!-- Lý do hủy đơn -->
                <div class="form-group">
                    <label><strong>Lý do hủy đơn:</strong></label>
                    <!-- Radio Button -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="noNeed" name="cancelReason" value="noNeed" checked>
                        <label class="custom-control-label" for="noNeed">Tôi không có nhu cầu mua nữa</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="changeAddress" name="cancelReason" value="changeAddress">
                        <label class="custom-control-label" for="changeAddress">Tôi muốn đổi địa chỉ</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="changeColorSize" name="cancelReason" value="changeColorSize">
                        <label class="custom-control-label" for="changeColorSize">Tôi muốn thay đổi màu sắc, kích cỡ</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="otherReason" name="cancelReason" value="other">
                        <label class="custom-control-label" for="otherReason">Lý do khác</label>
                    </div>
                </div>

                <!-- Lý do khác (hiển thị khi chọn "Lý do khác") -->
                <div class="form-group" id="otherReasonDiv" style="display:none;">
                    <label for="otherReasonInput">Vui lòng nhập lý do:</label>
                    <input type="text" class="form-control" id="otherReasonInput" placeholder="Nhập lý do hủy">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-danger">Xác Nhận Hủy</button>
            </div>
        </div>
    </div>
</div>

FashionShop/Views/Shared/MyAccount.cshtml
@using FashionShop.Models.LeDucThien.ThienProcessData;
@{
    Layout = null;

    HttpCookie usernameCookie = Request.Cookies["Username"];
    var username = usernameCookie != null ? usernameCookie.Value : string.Empty;

    pd_KhachHang khachHangProcess = new pd_KhachHang();

    var user = khachHangProcess.GetKhachHangWhere(username).FirstOrDefault();

    ViewBag.AnhSideBar = user.Anh;
    ViewBag.UsernameSideBar = user.Username;
}

<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body>
    @Html.Partial("_Header")

    <div class="container-fluid mb-5">
        <div class="row px-xl-5">
            <!-- Phần 1 -->
            <div class="col-md-4">
                @Html.Partial("SideBarMyAccount")
            </div>
            <!-- Phần 2 -->
            <div class="col-md-8 bg-secondary p-3">
                @RenderBody()
            </div>
        </div>
    </div>

    @Html.Partial("_Footer")


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="~/mail/jqBootstrapValidation.min.js"></script>
    <script src="~/mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
</body>

</html>

FashionShop/Views/Shared/SideBarMyAccount.cshtml
@{
    Layout = null;
}

<div class="p-0 d-flex align-items-center">
    <div class="p-3">
        <img src="@Url.Content(ViewBag.AnhSideBar)" alt="Avatar" class="rounded rounded-circle border-dark" style="width: 50px; height: 50px; object-fit: cover;">
    </div>
    <div class="ml-3">
        <h6>@ViewBag.UsernameSideBar</h6>
    </div>
</div>


<nav class="navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0">
    <div class="navbar-nav w-100 overflow-hidden">
        <!-- Dropdown Tài khoản của tôi -->
        <div class="nav-item dropdown">
            <a href="#" class="nav-link" data-toggle="dropdown">
                <i class="fa-regular fa-user mr-1" style="color: #205dc5;"></i> Tài khoản của tôi
            </a>
            <div class="dropdown-menu w-100 position-relative" aria-labelledby="dropdownAccount">
                <a class="dropdown-item @Html.Raw(@ViewBag.Title.Equals("HoSo") ? "active" : "")" href="@Url.Action("HoSo", "MyAccount")">Hồ sơ</a>
                <a class="dropdown-item @Html.Raw(@ViewBag.Title.Equals("NganHang") ? "active" : "")" href="@Url.Action("NganHang", "MyAccount")">Ngân hàng</a>
                <a class="dropdown-item @Html.Raw(@ViewBag.Title.Equals("DiaChi") ? "active" : "")" href="@Url.Action("DiaChi", "MyAccount")">Địa chỉ</a>
                <a class="dropdown-item @Html.Raw(@ViewBag.Title.Equals("MatKhau") ? "active" : "")" href="@Url.Action("MatKhau", "MyAccount")">Đổi mật khẩu</a>
            </div>
        </div>

        <a href="@Url.Action("order", "Order")" class="nav-item nav-link @Html.Raw(@ViewBag.Title.Equals("Order") ? "active" : "")">
            <i class="fa-solid fa-list mr-1" style="color: #205dc5;"></i> Đơn mua
        </a>

        <!-- Dropdown Thông báo -->
        <div class="nav-item dropdown">
            <a href="#" class="nav-link" data-toggle="dropdown">
                <i class="fa-regular fa-bell mr-1" style="color: #e74c3c;"></i> Thông báo
            </a>
            <div class="dropdown-menu w-100 position-relative" aria-labelledby="dropdownNotification">
                <a class="dropdown-item @Html.Raw(@ViewBag.Title.Equals("CapNhatDonHang") ? "active" : "")" href="@Url.Action("CapNhatDonHang", "Notification")">Cập nhật đơn hàng</a>
            </div>
        </div>

        <a href="@Url.Action("voucher", "Voucher")" class="nav-item nav-link @Html.Raw(@ViewBag.Title.Equals("Voucher") ? "active" : "")">
            <i class="fa-solid fa-ticket mr-1" style="color: #e74c3c;"></i> Kho voucher
        </a>
    </div>
</nav>

FashionShop/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}

<!-- Footer Start -->
<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-6 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="@Url.Action("Index", "Home")" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
            </a>
            <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-6 col-md-12">
            <div class="row">
                <div class="col-md-6 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="@Url.Action("Index", "Home")"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="@Url.Action("product", "Shop")"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark" href="@Url.Action("contact", "Contact")"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-6 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                   required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed
                by
                <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="~/img/payments.png" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>